### ISSUE TITLE
Feature Request: connections registry

### ISSUE THREAD

**Issue by gui-salome** [Salompas/credo#8]
Create a configuration file that has default specifications for connecting to certain databases and allows users to extend it to connect to others. For example, a YAML file with:
```
Redshift:
  - connection:
    - driver:
    - host:
    - port:
    - database:
    - timeout:
  - catalog:
    - name
    - load
    - save 
```
